import type { MarketplaceState } from "./types";

export const seedState: MarketplaceState = {
  participants: [
    {
      id: "buyer-1",
      role: "buyer",
      name: "Elena Markovic",
      company: "Northbridge Capital",
      email: "elena@northbridge.example",
      location: "London, UK",
      status: "active",
      tags: ["strategic buyer", "software", "western europe"],
      createdAt: "2026-04-02",
    },
    {
      id: "buyer-2",
      role: "buyer",
      name: "Mateo Ruiz",
      company: "Iberia Growth Partners",
      email: "mateo@iberiagrowth.example",
      location: "Madrid, Spain",
      status: "active",
      tags: ["private equity", "healthcare", "buyout"],
      createdAt: "2026-04-16",
    },
    {
      id: "buyer-3",
      role: "buyer",
      name: "Sofia Petrov",
      company: "Black Sea Holdings",
      email: "sofia@bsh.example",
      location: "Sofia, Bulgaria",
      status: "suspended",
      tags: ["family office", "industrial", "cee"],
      createdAt: "2026-05-04",
    },
    {
      id: "seller-1",
      role: "seller",
      name: "Daniel Hart",
      company: "Hart Advisory",
      email: "daniel@hartadvisory.example",
      location: "Berlin, Germany",
      status: "active",
      tags: ["advisor", "sell-side", "saas"],
      createdAt: "2026-03-21",
    },
    {
      id: "seller-2",
      role: "seller",
      name: "Mira Novak",
      company: "Novak Ventures",
      email: "mira@novak.example",
      location: "Prague, Czechia",
      status: "active",
      tags: ["owner", "energy", "minority stake"],
      createdAt: "2026-05-11",
    },
    {
      id: "manager-1",
      role: "manager",
      name: "Alex Morgan",
      company: "N5Deal",
      email: "alex@n5deal.example",
      location: "Remote",
      status: "active",
      tags: ["platform", "compliance"],
      createdAt: "2026-02-01",
    },
  ],
  buyerProfiles: [
    {
      participantId: "buyer-1",
      ticketMin: 5,
      ticketMax: 35,
      targetRegions: ["Western Europe", "Nordics"],
      targetSectors: ["SaaS", "Fintech", "B2B Services"],
      interestText: "Profitable B2B software companies with recurring revenue and clear expansion potential.",
      mandateStage: "Active mandate",
    },
    {
      participantId: "buyer-2",
      ticketMin: 10,
      ticketMax: 60,
      targetRegions: ["Spain", "Portugal", "Western Europe"],
      targetSectors: ["Healthcare", "Diagnostics", "Medtech"],
      interestText: "Control investments in healthcare platforms with resilient demand and operational upside.",
      mandateStage: "Screening",
    },
    {
      participantId: "buyer-3",
      ticketMin: 3,
      ticketMax: 20,
      targetRegions: ["CEE", "Balkans"],
      targetSectors: ["Industrial", "Energy", "Logistics"],
      interestText: "Asset-heavy businesses with defensible local market positions.",
      mandateStage: "Paused",
    },
  ],
  assets: [
    {
      id: "asset-1",
      sellerId: "seller-1",
      title: "Vertical SaaS Platform for Field Service Teams",
      type: "Majority stake",
      sector: "SaaS",
      region: "Western Europe",
      priceMin: 12,
      priceMax: 18,
      ebitda: 2,
      description: "Subscription software business with 92% net revenue retention and a specialized workflow product.",
      status: "published",
      createdAt: "2026-06-01",
    },
    {
      id: "asset-2",
      sellerId: "seller-2",
      title: "Distributed Solar Portfolio",
      type: "Minority stake",
      sector: "Energy",
      region: "CEE",
      priceMin: 8,
      priceMax: 14,
      ebitda: 1,
      description: "Operating renewable assets with contracted revenue and expansion pipeline across CEE.",
      status: "published",
      createdAt: "2026-06-12",
    },
    {
      id: "asset-3",
      sellerId: "seller-1",
      title: "Specialized Diagnostic Clinics Network",
      type: "Buyout",
      sector: "Healthcare",
      region: "Spain",
      priceMin: 28,
      priceMax: 45,
      ebitda: 5,
      description: "Regional diagnostics provider with modern equipment, strong physician referral base and room for consolidation.",
      status: "published",
      createdAt: "2026-07-02",
    },
  ],
  contacts: [
    {
      id: "contact-1",
      fromId: "buyer-1",
      toId: "seller-1",
      assetId: "asset-1",
      message: "Interested in the SaaS opportunity. Please share the teaser and NDA process.",
      createdAt: "2026-07-10",
    },
  ],
};

export function cloneSeedState(): MarketplaceState {
  return JSON.parse(JSON.stringify(seedState)) as MarketplaceState;
}
